# Use the node image from official Docker Hub
FROM node:16.10.0-alpine3.13 as build-stage
# set the working directory
WORKDIR /
# Copy the working directory in the container
COPY package*.json ./
# Install the project dependencies
RUN npm install
# Copy the rest of the project files to the container
COPY . .
ENV VITE_API_V1_CANNONICAL="https://x8ki-letl-twmt.n7.xano.io/api:NYm9JgOK"
ENV VITE_AUTHENTICATION_CANNONICAL="https://x8ki-letl-twmt.n7.xano.io/api:yXLVtVR9"
ENV VITE_GOOGLE_OAUTH_CANNONICAL="https://x8ki-letl-twmt.n7.xano.io/api:Fcy4VpNc"
ENV VITE_BACKEND_TECHNOLOGY="XANO"
# Build the Vue.js application to the production mode to dist folder
RUN npm run build
# Use the lightweight Nginx image from the previous stage for the nginx container
FROM nginx:stable-alpine as production-stage
# Copy the build application from the previous stage to the Nginx container
COPY --from=build-stage /dist /usr/share/nginx/html
# Copy the nginx configuration file
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Expose the port 80
EXPOSE 80
# Start Nginx to serve the application
CMD ["nginx", "-g", "daemon off;"]